name: Domain Analysis

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  analysis:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python version
        run: python3 --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run pipeline
        run: |
          PYTHONPATH=. python scripts/run_pipeline.py https://www.attuario.eu \
          --max-pages 50 \
          --max-depth 2 \
          --delay 0.5 \
          --output-dir outputs

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: attuario-eu-report
          path: outputs/*
