name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install flake8 black

      - name: Run flake8
        run: flake8 attuario_ai scripts tests

      - name: Run black check
        run: black --check attuario_ai scripts tests
