name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install flake8 black

      - name: Run flake8
        run: flake8 attuario_ai scripts tests

      - name: Run black
        run: black --check attuario_ai scripts tests
