name: Pylint

on:
  schedule:
    - cron: "0 6 * * *"   # tutti i giorni alle 6:00 UTC
  workflow_dispatch:       # avvio manuale

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --no-cache-dir -r requirements-dev.txt


      - name: Analisi con pylint
        run: pylint $(git ls-files '*.py')
