name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --no-cache-dir -r requirements-dev.txt

      - name: Run lint
        run: |
          source .venv/bin/activate
          black --check .
          flake8 .
