name: Tests

on:
  schedule:
    - cron: "0 6 * * *"   # tutti i giorni alle 6:00 UTC
  workflow_dispatch:       # avvio manuale da GitHub UI

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Usa Python locale
        run: python3 --version
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -v
