name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: self-hosted   # forza uso del tuo runner
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (skip official setup, already present on runner)
        run: python3 --version

      - name: Install dependencies
        run: |
          pip install --user -r requirements.txt
          pip install --user pytest

      - name: Run tests
        run: pytest -v
